import funk.gui.core.Component;
import funk.gui.core.ComponentModel;
import funk.gui.core.ComponentObserver;
import funk.gui.core.ComponentState;
import funk.gui.core.ComponentView;
import funk.gui.core.Container;
import funk.gui.core.events.ComponentEvent;
import funk.gui.core.observables.ComponentModelObserver;
import funk.gui.core.observables.ComponentStateObserver;
class All{}